name: AtlasCI

on:
  push:
    branches:
      - "master"
      - "it-3"
  pull_request:
    branches:
      - "master"
      - "it-3"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    
    - name: Build app
      run: ./gradlew assembleDebug assembleAndroidTest
    
    - name: List APK files for debugging
      run: ls -R app/build/outputs/apk
    
    - name: Run tests
      uses: emulator-wtf/run-tests@v0
      with:
        api-token: ${{ secrets.EW_API_TOKEN }}
        app: app/build/outputs/apk/debug/app-debug.apk
        test: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
        outputs-dir: build/test-results
    
    - name: Publish test report
      uses: mikepenz/action-junit-report@v2
      if: always() # always run even if the tests fail
      with:
        report_paths: 'build/test-results/**/*.xml'
